# Generated by Django 5.0.7 on 2024-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0002_officemanager_sallary_delete_offceadmin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sallary',
        ),
        migrations.AlterField(
            model_name='officemanager',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='officemanager',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
