# Generated by Django 5.0.7 on 2024-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0004_officemanager_user_officeuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officeuser',
            name='staff_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='officeuser',
            name='staff_pic',
            field=models.ImageField(blank=True, null=True, upload_to='staff_pics/'),
        ),
    ]
