# Generated by Django 5.0.7 on 2024-08-06 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0005_officeuser_address_officeuser_staff_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='wait_time_finish',
        ),
        migrations.RemoveField(
            model_name='clock',
            name='wait_time_start',
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('leave_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('office_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftarMain.officeuser')),
            ],
        ),
    ]
