# Generated by Django 5.0.7 on 2024-08-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0006_remove_clock_wait_time_finish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
