# Generated by Django 5.0.7 on 2024-08-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0010_alter_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved',
            field=models.BooleanField(default=None),
        ),
    ]
