# Generated by Django 5.0.7 on 2024-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0012_alter_leave_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='clock_entries', to='daftarMain.project'),
        ),
    ]
