# Generated by Django 5.0.7 on 2024-08-12 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0013_clock_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_hours_worked',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_spent', models.FloatField(default=0)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('office_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftarMain.officeuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftarMain.project')),
            ],
            options={
                'unique_together': {('office_user', 'project', 'log_date')},
            },
        ),
    ]
