# Generated by Django 5.0.7 on 2024-08-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0014_project_total_hours_worked_projecttimelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total_hours_worked',
        ),
    ]
