# Generated by Django 5.0.7 on 2024-08-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0015_remove_project_total_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeuser',
            name='have_bime',
            field=models.BooleanField(default=False),
        ),
    ]
