# Generated by Django 5.0.7 on 2024-08-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0016_officeuser_have_bime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officemanager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='officemanager',
            name='last_name',
        ),
        migrations.AddField(
            model_name='officemanager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='officemanager',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
