# Generated by Django 5.1 on 2024-08-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0017_remove_officemanager_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='is_reward_punishment',
            field=models.BooleanField(default=False),
        ),
    ]
