# Generated by Django 5.1 on 2024-08-17 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0018_clock_is_reward_punishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeuser',
            name='childeren_count',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='officeuser',
            name='code_bime',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='officeuser',
            name='family_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='officeuser',
            name='marital_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeuser',
            name='military_service_status',
            field=models.CharField(choices=[('COM', 'Complete'), ('PEN', 'Pending'), ('N/A', 'Do not have')], default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='clock',
            name='office_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='daftarMain.officeuser'),
        ),
    ]
