# Generated by Django 5.1 on 2024-09-01 06:43

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0019_officeuser_childeren_count_officeuser_code_bime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
