# Generated by Django 5.1 on 2024-09-01 09:21

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0020_alter_leave_end_date_alter_leave_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='entry_to_office',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clock',
            name='exit_from_office',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officemanager',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='projecttimelog',
            name='log_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='regularrequest',
            name='submitted_at',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
