# Generated by Django 5.1 on 2024-09-03 07:24

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftarMain', '0021_alter_clock_entry_to_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='entry_to_office',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clock',
            name='exit_from_office',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
